apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-server
  template:
    metadata:
      labels:
        app: python-server
    spec:
      containers:
      - name: python-server
        image: ml-hw-python-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        - containerPort: 65432

---
apiVersion: v1
kind: Service
metadata:
  name: python-server-service
spec:
  type: NodePort
  selector:
    app: python-server
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      nodePort: 30001
      name: http
    - port: 65432
      targetPort: 65432
      protocol: TCP
      name: websocket

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-client
  template:
    metadata:
      labels:
        app: python-client
    spec:
      containers:
      - name: python-client
        image: ml-hw-python-client:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: WEBSOCKET_SERVER_HOST
            value: "python-server-service"
          - name: WEBSOCKET_SERVER_PORT
            value: "65432"
