apiVersion: v1
kind: Service
metadata:
  name: python-server-service
spec:
  type: NodePort
  selector:
    app: python-server
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      nodePort: 30001
      name: http
    - port: 65432
      targetPort: 65432
      protocol: TCP
      name: websocket